spring.application.name=gateway-ms
server.port=9090

logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping=TRACE

management.endpoints.web.exposure.include=*

# User Service
spring.cloud.gateway.server.webflux.routes[0].id=user-ms
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:9091
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/user/**
#spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1